### ISSUE TITLE
Carte 3 : Contact + Map

### ISSUE THREAD

**Issue by Cha1ymae** [AmnezziaCS/HoudiPizza#10]
En tant que client, 
je veux pouvoir localiser HoudiPizza  " 6 Rue Rihour " et pouvoir contacter la pizzeria par téléphone "06 06 06 06 06" .

**Comment by Hugo59530** [comment]
1. Affichage de la localisation

    Critère 1.1 : La page doit afficher clairement l'adresse complète de HoudiPizza : "6 Rue Rihour".
    Critère 1.2 : Un lien vers une carte interactive (Google Maps ou autre service de cartographie) doit être présent. Ce lien doit permettre de localiser la pizzeria en un clic.
    Critère 1.3 : Lorsque l'utilisateur clique sur le lien de la carte, la localisation de HoudiPizza (6 Rue Rihour) doit s'ouvrir directement sur l'application de cartographie dans une nouvelle fenêtre.
    Critère 1.4 : La carte doit être responsive et accessible sur mobile, permettant à l'utilisateur de naviguer facilement à partir de son smartphone.

2. Affichage et fonctionnalité du contact téléphonique

    Critère 2.1 : Le numéro de téléphone de la pizzeria (06 06 06 06 06) doit être affiché de manière visible et lisible sur la page (section contact ou en haut du site).
    Critère 2.2 : Le numéro doit être cliquable pour les utilisateurs sur mobile, permettant d'initier un appel directement en un seul clic (via un lien de type tel:).
    Critère 2.3 : Le numéro de téléphone doit être valide et fonctionnel, avec une vérification manuelle que l'appel arrive bien à la pizzeria.

3. Conception et UX

    Critère 3.1 : Les nouvelles sections (adresse et téléphone) doivent être intégrées dans le design existant du site, avec une cohérence visuelle et ergonomique.
    Critère 3.2 : L'ajout de ces informations ne doit pas altérer la rapidité ou la fluidité de navigation du site.

4. Tests de compatibilité

    Critère 4.1 : Les fonctionnalités de localisation et de contact téléphonique doivent être testées et fonctionner sur les principaux navigateurs (Chrome, Firefox, Safari) et sur les plateformes mobiles (iOS et Android).
    Critère 4.2 : La carte interactive et le numéro de téléphone doivent être facilement utilisables sur les écrans de différentes tailles (desktop, tablette, mobile).

5. Accessibilité

    Critère 5.1 : Les informations de contact (adresse et téléphone) doivent être accessibles aux personnes utilisant des lecteurs d’écran.
    Critère 5.2 : Les boutons et liens doivent être suffisamment contrastés et grands pour être cliqués facilement par les utilisateurs avec des besoins particuliers.
