### ISSUE TITLE
Carte 5 : Créer la page de login client

### ISSUE THREAD

**Issue by AmnezziaCS** [AmnezziaCS/HoudiPizza#14]
En tant que responsable de la pizzeria, je souhaite pouvoir me connecter sur la page `/admin` avec mon (`login: admin`) et mon (`mot de passe: pizza`).

## Technical tasks

- Créer la page `/admin`
- Autoriser le login uniquement avec (`login: admin`) et (`mot de passe: pizza`).

**Comment by Cha1ymae** [comment]
1. L'admin doit avoir la possibilité d'accéder à une page /admin.
2. L'admin doit avoir la possibilité de se connecter qu'avec un **login** : _admin_ et un mot de passe **mot de passe** : _pizza_.
3. Les clients doivent pas avoir accès à :  /admin.
