### ISSUE TITLE
Carte 7 : Créer la page détail par pizza

### ISSUE THREAD

**Issue by AmnezziaCS** [AmnezziaCS/HoudiPizza#16]
En tant que client de la pizzeria, je souhaite pouvoir, avoir accès à la page détails d'une pizza.

## Technical tasks

- Créer une page /pizzas/[id] par pizza.
- La page est accessible en cliquant sur le nom hypertexte du menu de la pizza.
- Sur chaque page, afficher `nom, description, prix, taille, image` de la pizza.

**Comment by Cha1ymae** [comment]
1. Les clients doivent avoir la possibilité de consulter les détails d'une pizza dans une page /pizzas/[id], après avoir cliqué sur le nom de la pizza.
2. Les clients doivent avoir la possibilité de voir le nom, description , prix , taille et une image des pizzas.

**Comment by AmnezziaCS** [comment]
fixed by #18
