### ISSUE TITLE
Carte 1 : Création page principale 

### ISSUE THREAD

**Issue by Cha1ymae** [AmnezziaCS/HoudiPizza#8]
En tant que client, je veux pouvoir accéder au site HoudiPizza, un site inspiré de [Five Pizza](https://fivepizzaoriginal.com/fr_fr/) deux couleurs principaux orange et bleu, une page web de single page, les composants de la page : 

1. Logo HoudiPizza 
2. Des bouttons qui vont lier les différents blocs de la page 
3. Bloc 1 :  petite présentation pour HoudiPizza 
4. Bloc 2 : Menu  de pizza 
5. Bloc 3 :  Maps + contact
6. Bloc 4 : Réseau sociaux

**Comment by Hugo59530** [comment]
Critère d'acceptation :

Nous retrouvons la chartre graphique demandé par le client (Logo, Couleurs)
nous retrouvons la présentation de la pizzeria
nous retrouvons une carte complète (images, tailles, prix, description)
nous retrouvons l’adresse et une carte avec indiqué dessus l’emplacement de la pizzeria
nous retrouvons les information de contacts de la pizzeria
nous retrouvons des liens fonctionnels vers les différents réseaux sociaux 
Les boutons sont bien intégré et fonctionnel 
le carrousels d'images est fluides
